#!/bin/bash

# Install common Homebrew formulae
#
# You must first install Xcode, open it, and agree to the license
#
# Credits:
# necolas/dotfiles
# mathiasbynens/dotfiles

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

# Install RingoJS and Narwhal
# Note that the order in which these are installed is important; see http://git.io/brew-narwhal-ringo.
brew install ringojs
brew install narwhal

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew tap josegonzalez/homebrew-php
brew install php54

# Install everything else
brew install ack
#brew install exiv2
brew install git
brew install imagemagick
brew install lynx
brew install node
brew install rename
brew install rhino
brew install tree
brew install webkit2png
brew install bash-completion
brew install optipng
# See http://superuser.com/questions/334252/the-best-way-to-make-macvims-vim-console-not-mvim-the-default-instead-of-mac
brew install macvim --override-system-vim
brew install phantomjs
brew install trash
# ledger 3.0: http://comments.gmane.org/gmane.comp.finance.ledger.general/3915
brew install --HEAD --python ledger
# MPD and dependencies
brew install libzzip
brew install mpd

# Remove outdated versions from the cellar
brew cleanup
