echo "Hello, this is zshrc calling."

# Source aliases and private files
source ~/dotfiles/aliases
source ~/.secrets

# Set up PATH
# Ensure user-installed binaries take precedence
export PATH=/usr/local/share/python:/usr/local/share/python3:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MAMP/Library/bin

# Enable advanced tab-completion
autoload -Uz compinit
compinit

# Enable autocorrect
setopt correctall

# Enable advanced prompts
autoload -Uz promptinit
promptinit

# Enable gathering of VCS information for Git and SVN
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
zstyle ':vcs_info:*' check-for-changes true # potential performance drag
setopt prompt_subst

# Customize the prompt
export PROMPT='%~ : ) '
export RPROMPT='${vcs_info_msg_0_}'

# Enable autocd
setopt autocd

# Enable extended globbing
setopt extendedglob

# Keep 2000 lines of history within the shell and save them to ~/.zsh_history:
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history

# Add timestamps to history
setopt EXTENDED_HISTORY

# Write a home folder-based `cd` command from any directory
CDPATH=~

# Allow autocompletions based on substrings
if [ "x$CASE_SENSITIVE" = "xtrue" ]; then
  zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
  unset CASE_SENSITIVE
else
  zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
fi

# Use vi keybindings
bindkey -v

# Use Ctrl-r for incremental history searches
bindkey '^r' history-incremental-search-backward

# Use emacs-style keybindings for jumping to line endings or beginnings
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# vim is our editor
export EDITOR=vim

# Makes a directory and changes to it.
function mkdcd {
  [[ -n "$1" ]] && mkdir -p "$1" && builtin cd "$1"
}

# Bind Fn+Delete to forward-delete
bindkey "^[[3~" delete-char

# Expand .... to ../..
function expand-dot-to-parent-directory-path {
  if [[ $LBUFFER = *.. ]]; then
    LBUFFER+='/..'
  else
    LBUFFER+='.'
  fi
}
zle -N expand-dot-to-parent-directory-path
bindkey "." expand-dot-to-parent-directory-path

# Source autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# Do just before presenting the prompt
precmd () {
  vcs_info
}

# Sources:
# Everything in the `community` directory
# www.gentoo.org/doc/en/zsh.xml
# The .zshrc that came with a Dreamhost shell
# http://zsh.sourceforge.net/Intro/intro_13.html
# https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/completion.zsh
# https://github.com/skwp/dotfiles/tree/master/zsh
# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
# http://zsh.git.sourceforge.net/git/gitweb.cgi?p=zsh/zsh;a=blob;f=Functions/Prompts/prompt_walters_setup
# http://arjanvandergaag.nl/blog/customize-zsh-prompt-with-vcs-info.html
# http://unix.stackexchange.com/a/14267
# https://github.com/holman/dotfiles/blob/master/zsh/config.zsh
# http://hackercodex.com/guide/mac-osx-mountain-lion-10.8-configuration/
# http://superuser.com/questions/169920/binding-fn-delete-in-zsh-on-mac-os-x
