#!/bin/bash

# bash_profile

echo "Hello, this is bash_profile calling."

declare -a files=(
    $HOME/dotfiles/bash/bash_config # Configuration
    $HOME/dotfiles/bash/bash_aliases # Aliases
    $HOME/dotfiles/bash/bash_prompt # Custom bash prompt
    $HOME/.secrets # Local and private settings not under version control (e.g. git credentials)
    $HOME/dotfiles/bash/bash_paths # Path modifications (must source after `.secrets` in case of custom `brew` location)
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
	echo "Sourcing" ${files[$index]}
        source ${files[$index]}
    fi
done

unset files

# Only use `brew` after it has been added to the PATH
bash_completion_path="$(brew --prefix)/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi

# Source autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
