#!/bin/bash

# inputrc

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list tab completions (use instead of TAB-cycling)
set show-all-if-ambiguous on

# Make TAB cycle through possible completions
"\t": menu-complete
# Make SHIFT-TAB reverse cycle through possible completions
"\e[Z": "\e-1\C-i"

# Use the string that has already been typed as the prefix for searching
# through commands (i.e. more intelligent Up/Down-arrow behavior)
"\e[B": history-search-forward
"\e[A": history-search-backward

# Make Ctrl-W erase words in a string, not until the first space
# http://superuser.com/questions/212446/binding-backward-kill-word-to-ctrlw
set bind-tty-special-chars off
"\C-w": backward-kill-word
